version: '3.8'

services:
  fastapi-app:
    build: .
    ports:
      - "443:8000"
    volumes:
      - .:/app
    # Ensure your cert files are in the context and used by the app
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"